//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package net.netdatacorp.efile.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NotifyCaseAssignmentCompleteResp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NotifyCaseAssignmentCompleteResp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NotifyCaseAssignmentCompleteResponse" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NotifyCaseAssignmentCompleteResp", propOrder = {
    "NotifyCaseAssignmentCompleteResponse"
})
public class NotifyCaseAssignmentCompleteResp {

    @XmlElement(name = "NotifyCaseAssignmentCompleteResponse")
    protected Object NotifyCaseAssignmentCompleteResponse;

    /**
     * Gets the value of the NotifyCaseAssignmentCompleteResponse property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getNotifyCaseAssignmentCompleteResponse() {
        return NotifyCaseAssignmentCompleteResponse;
    }

    /**
     * Sets the value of the NotifyCaseAssignmentCompleteResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setNotifyCaseAssignmentCompleteResponse(Object value) {
        this.NotifyCaseAssignmentCompleteResponse = value;
    }

}
