//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package net.netdatacorp.efile.service;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the oasis.names.tc.legalxml_courtfiling.wsdl.webservicemessagingprofile_definitions_4 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _NotifyDocketingComplete_QNAME = new QName("urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitions-4.0", "NotifyDocketingComplete");
    private final static QName _NotifyDocketingCompleteResp_QNAME = new QName("urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitions-4.0", "NotifyDocketingCompleteResp");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: oasis.names.tc.legalxml_courtfiling.wsdl.webservicemessagingprofile_definitions_4
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NotifyDocketingCompleteResp }
     * 
     */
    public NotifyDocketingCompleteResp createNotifyDocketingCompleteResp() {
        return new NotifyDocketingCompleteResp();
    }

    /**
     * Create an instance of {@link NotifyDocketingComplete }
     * 
     */
    public NotifyDocketingComplete createNotifyDocketingComplete() {
        return new NotifyDocketingComplete();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotifyDocketingComplete }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitions-4.0", name = "NotifyDocketingComplete")
    public JAXBElement<NotifyDocketingComplete> createNotifyDocketingComplete(NotifyDocketingComplete value) {
        return new JAXBElement<NotifyDocketingComplete>(_NotifyDocketingComplete_QNAME, NotifyDocketingComplete.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotifyDocketingCompleteResp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitions-4.0", name = "NotifyDocketingCompleteResp")
    public JAXBElement<NotifyDocketingCompleteResp> createNotifyDocketingCompleteResp(NotifyDocketingCompleteResp value) {
        return new JAXBElement<NotifyDocketingCompleteResp>(_NotifyDocketingCompleteResp_QNAME, NotifyDocketingCompleteResp.class, null, value);
    }

}
