//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.13 at 12:44:18 AM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitions-4.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.netdatacorp.efile.service;
