//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package net.netdatacorp.efile.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "SvcProdPortType", targetNamespace = "urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitions-4.0")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SvcProdPortType {


    /**
     * 
     * @param notifyDocketingCompleteRequest
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(operationName = "NotifyDocketingComplete")
    @WebResult(name = "NotifyDocketingCompleteResponse", targetNamespace = "")
    @RequestWrapper(localName = "NotifyDocketingComplete", targetNamespace = "urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitions-4.0", className = "oasis.names.tc.legalxml_courtfiling.wsdl.webservicemessagingprofile_definitions_4.NotifyDocketingComplete")
    @ResponseWrapper(localName = "NotifyDocketingCompleteResp", targetNamespace = "urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitions-4.0", className = "oasis.names.tc.legalxml_courtfiling.wsdl.webservicemessagingprofile_definitions_4.NotifyDocketingCompleteResp")
    public Object notifyDocketingComplete(
        @WebParam(name = "NotifyDocketingCompleteRequest") //, targetNamespace = "")
        Object notifyDocketingCompleteRequest);

    /**
     * 
     * @param NotifyCaseAssignmentCompleteRequest
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(operationName = "NotifyCaseAssignmentComplete")
    @WebResult(name = "NotifyCaseAssignmentCompleteResponse", targetNamespace = "")
    @RequestWrapper(localName = "NotifyCaseAssignmentComplete", targetNamespace = "urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitions-4.0", className = "oasis.names.tc.legalxml_courtfiling.wsdl.webservicemessagingprofile_definitions_4.NotifyCaseAssignmentComplete")
    @ResponseWrapper(localName = "NotifyCaseAssignmentCompleteResp", targetNamespace = "urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitions-4.0", className = "oasis.names.tc.legalxml_courtfiling.wsdl.webservicemessagingprofile_definitions_4.NotifyCaseAssignmentCompleteResp")
    public Object notifyCaseAssignmentComplete(
        @WebParam(name = "NotifyCaseAssignmentCompleteRequest") //, targetNamespace = "")
        Object notifyCaseAssignmentCompleteRequest);

}
